import type { Metadata } from 'next';
import { Geist, Geist_Mono, Bree_Serif, Open_Sans } from 'next/font/google';
import './globals.css';
import HeaderComponent from '@/components/header';
import FooterComponent from '@/components/footer';

const breeSerif = Bree_Serif({
  variable: "--font-bree-Serif",
  subsets: ["latin"],
  weight: "400"
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${breeSerif.variable} ${openSans.variable} antialiased`}
      >
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
